### ISSUE TITLE
Include Testing Environment for JS

### ISSUE THREAD

**Issue by noegeler** [d-lama/d-lama-webapp#3]
**Link to User Story**
[1013](https://github.com/d-lama/.github/blob/main/mgmt/product_backlog.md#1013)

**Feature Description**
Search Testing possibilities and integrate the testing environment in the project repository

- [x] find possible, sensible testing possibilities
- [x] decide on the best ones
- [x] include in project

**Additional context**
To develop in a test driven environment, testing libraries must be defined and included in the project

**Comment by schazadm** [comment]
Started with `react-scripts` to execute the commands and `jest` as the unit test library.
Didn't work well with `ionic` because the unit tests didn't properly detect the ionic components.

Did some research and tried to pull a pre-built react-ionic app and look for their approach.
Found out that the ionic team and most people use `vite` as their tooling library to execute runners and `vitest` as their unit test framework.
In addition, the end-to-end testing framework `cypress` was used for automated integration testing.

I included `vite`, `vitest` and `cypress` in the project and created a sample test.
